name: simple_file_saver_android_example
description: Demonstrates how to use the simple_file_saver_android plugin.
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  simple_file_saver_android:
    path: ../

  simple_file_saver_platform_interface: ^2.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true