name: simple_file_saver_android
description: Android implementation of the simple_file_saver plugin.
homepage: https://github.com/LaemonT/simple_file_saver
repository: https://github.com/LaemonT/simple_file_saver/tree/main/simple_file_saver_android
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: simple_file_saver
    platforms:
      android:
        package: com.laemont.simple_file_saver
        pluginClass: SimpleFileSaverPlugin
        dartPluginClass: SimpleFileSaverAndroid

dependencies:
  flutter:
    sdk: flutter
  simple_file_saver_platform_interface:
    path: ../simple_file_saver_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^17.2.0

topics:
  - files
  - save-file
  - file-saver