name: simple_file_saver_platform_interface
description: A common platform interface for the simple_file_saver plugin.
homepage: https://github.com/LaemonT/simple_file_saver
repository: https://github.com/LaemonT/simple_file_saver/tree/main/simple_file_saver_platform_interface
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.2.6
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - files
  - save-file
  - file-saver